config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  scope "/manage" do
    resources :posts do
      member do
        get :pin
        get :unpin
      end
    end
    get "/user_posts", to: "posts#user_posts", as: :user_posts
    get "/redirect_posts", to: "posts#redirect_posts", as: :redirect_posts
    get "posts/:id/download_as_zip", to: "posts#download_as_zip", as: :download_post_as_zip
    get "posts/unpin_all", to: "posts#unpin_all", as: :unpin_all
    get "posts/:id/password", to: "posts#password_prompt", as: "post_password"
    post "posts/:id/verify_password", to: "posts#verify_password", as: "verify_post_password"
  end

  constraints(slug: /[^\.\/]+/) do
    get "/:slug", to: "posts#handle_slug", as: :post_by_slug, constraints: lambda { |req|
      excluded_words = %w[manifest rails favicon]
      !excluded_words.include?(req.params[:slug])
    }
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_buttons.html.erb
<div class="col">
  <%= link_to "New Post", new_post_path, class: "btn #{current_page?(new_post_path) ? 'btn-secondary' : 'btn-outline-success'} float-end ms-2" %>
  <%= link_to "My Posts", user_posts_path, class: "btn #{current_page?(user_posts_path) ? 'btn-secondary' : 'btn-outline-secondary'} float-end ms-2" %>
  <%= link_to "Redirect Posts", redirect_posts_path, class: "btn #{current_page?(redirect_posts_path) ? 'btn-secondary' : 'btn-outline-secondary'} float-end ms-2" %>
  <%= link_to "Public Posts", posts_path, class: "btn #{current_page?(posts_path) ? 'btn-secondary' : 'btn-outline-secondary'} float-end" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark position-relative">
  <div class="container">
    <%= link_to "teleinf", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Home", posts_path, class: "nav-link #{current_page?(posts_path) ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
          <%= link_to "URLs", redirect_posts_path, class: "nav-link #{current_page?(redirect_posts_path) ? 'active' : ''}" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Posts", user_posts_path, class: "nav-link #{current_page?(user_posts_path) ? 'active' : ''}" %>
          </li>
        <% end %>
      </ul>

      <span class="mx-auto">
        <a href="https://ekursy.put.poznan.pl/" target="_blank" class="text-light text-decoration-none">
          <i class="fa-solid fa-graduation-cap"></i>
          <span class="ms-1">eKursy</span>
        </a>
      </span>


      <% if build = build_info and build[:sha] and build[:time] %>
        <div class="align-items-center text-light me-3" style="font-size: 0.8rem;">
          <span class="text-light text-decoration-none">
            <i class="bi bi-github"></i>
            <%= build[:sha][0..6] %>
            <span class="ms-1">
              <%= build[:time].in_time_zone('Europe/Warsaw').strftime('%b %d, %H:%M') %>
            </span>
          </span>
        </div>
      <% end %>


      <%= search_form_for @q, class: "search-form d-flex me-2" do |f| %>
        <%= f.search_field :title_or_description_or_slug_or_files_blobs_filename_cont,
                           class: "form-control search-input me-2",
                           placeholder: "Search" %>
        <%= f.submit "Search", class: "btn btn-outline-light" %>
      <% end %>

      <% if current_user %>
        <div class="btn-group me-2 mt-2 mt-md-0 float-end">
          <button type="button" class="btn btn btn-outline-primary"><%= current_user.username %></button>
          <button type="button" class="btn btn btn-outline-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", edit_user_registration_path, class: "dropdown-item disabled" %></li>
            <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item"%></li>
            <%# <li><a class="dropdown-item" href="#"></a></li> %>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item", form: { data: { turbo: false } } %></li>
          </ul>
        </div>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-primary me-2 mt-2 mt-md-0 float-end" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>dqq.pl <%= "- " if content_for(:title)%><%= content_for(:title) %></title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true, type: :module %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <% if Rails.application.config.analytics_url %>
      <script defer src="<%= Rails.application.config.analytics_url %>" data-website-id="<%= Rails.application.config.analytics_token %>"></script>
    <% end %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

  <style>
        body {
            background-color: #1e1f22;
            color: #f8f9fa;
        }
        .navbar {
            background-color: #212529;
        }
        .date-header {
            background-color: #2b2f34;
            border-radius: 5px;
            padding: 10px 15px;
            margin-top: 20px;
            margin-bottom: 15px;
            font-weight: 600;
            display: flex;
            align-items: center;
        }
        .date-header .date-icon {
            margin-right: 10px;
            color: #6c757d;
        }
        .text-muted {
            color:#484b4e !important;
        }
        .post-time {
            color: #6c757d;
            font-size: 0.85rem;
            margin-bottom: 5px;
        }
        .post-title {
            font-weight: 600;
            margin-bottom: 10px;
            color: #fff;
        }
        .post-description {
            color: #adb5bd;
            font-size: 0.9rem;
        }
        .file-list {
            list-style-type: none;
            padding-left: 0;
            margin-top: 15px;
        }
        .file-item {
            display: flex;
            align-items: center;
            padding: 5px 0;
        }
        .file-icon {
            margin-right: 10px;
            color: #6c757d;
        }
        .file-link {
            color: #0d6efd;
            text-decoration: none;
        }
        .file-link:hover {
            text-decoration: underline;
        }
        .nav-tabs {
            border-bottom: 1px solid #495057;
        }
        .nav-tabs .nav-link {
            color: #adb5bd;
            border: none;
        }
        .nav-tabs .nav-link.active {
            color: #fff;
            background-color: #343a40;
            border-bottom: 2px solid #0d6efd;
        }
        .btn-primary {
            background-color: #0d6efd;
            border-color: #0d6efd;
        }
        .search-form {
            display: flex;
        }
        .search-input {
            background-color: #2a2d31;
            border: 1px solid #6c757d;
            color: #f8f9fa;
            font-weight: 400;
            transition: all 0.2s ease-in-out;
        }
        .search-input::placeholder {
            color: #adb5bd;
            opacity: 0.8;
        }
        .search-input:focus {
            background-color: #212529;
            color: #fff;
            border-color: #0d6efd;
            box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
        }
        .sidebar-form {
            background-color: #2a2d31;
            border-radius: 5px;
            padding: 15px;
            position: sticky;
            top: 20px;
            margin-bottom: 20px;
        }
        .form-control, .form-select {
            background-color: #2c3035;
            border: 1px solid #495057;
            color: #fff;
        }
        .form-control:focus, .form-select:focus {
            background-color: #2c3035;
            color: #fff;
            border-color: #0d6efd;
        }
        .form-text {
            color: #adb5bd !important;
            font-size: 0.8rem;
        }
        .form-label {
            margin-bottom: 0.3rem;
            font-weight: 500;
        }
        .form-check-input {
            background-color: #2c3035;
            border: 1px solid #495057;
        }
        .form-check-input:checked {
            background-color: #0d6efd;
            border-color: #0d6efd;
        }
        textarea.form-control {
            min-height: 100px;
        }

        .post-card {
            background-color: #2a2d31;
            border: none;
            border-radius: 5px;
            margin-bottom: 15px;
            transition: transform 0.2s;
            position: relative
        }
        .post-card:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
        }

        .post-card .stretched-link {
          position: absolute;
          top: 0; left: 0;
          width: 100%; height: 100%;
          z-index: 1;
        }

        .post-card .file-link {
          position: relative;
          z-index: 2;
        }

        .post-card .post-redirect-url{
          position: relative;
          z-index: 2;
        }

        .post-card .post-x-link {
          position: relative;
          z-index: 3;
        }

        .sidebar-form {
            max-height: calc(100vh - 100px);
            overflow-y: auto;
            scrollbar-width: none; /* Firefox */
            -ms-overflow-style: none; /* IE and Edge */
        }

        .sidebar-form::-webkit-scrollbar {
            display: none; /* Chrome, Safari, Opera */
        }
    </style>

  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container text-white">
      <div class="mt-4">

        <% if notice %>
          <div class="alert alert-primary alert-dismissible fade show" role="alert"><%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <% if alert %>
          <div class="alert alert-primary alert-dismissible fade show" role="alert"><%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      </div>
      <%= yield %>

    </div>
  </body>

</html>